-- MySQL Script generated by MySQL Workbench
-- Wed Apr 11 23:06:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nargilemag
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nargilemag` ;

-- -----------------------------------------------------
-- Schema nargilemag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nargilemag` DEFAULT CHARACTER SET utf8 ;
USE `nargilemag` ;

-- -----------------------------------------------------
-- Table `nargilemag`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`users` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`users` (
  `id` INT(10) UNSIGNED NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `address` VARCHAR(255) NULL,
  `phone_number` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `nargilemag`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`orders` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`orders` (
  `id` INT(50) UNSIGNED NOT NULL,
  `date_of_issue` DATE NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_order_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_order_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `nargilemag`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `nargilemag`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`products` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`products` (
  `id` INT(50) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(350) NULL,
  `price` FLOAT UNSIGNED NOT NULL,
  `category`  ENUM('Hookah', 'Tobacco', 'BoxOfCubes'),
  `hookah_size`  ENUM('S', 'M', 'L'),
  `tobacco_flavor`  ENUM('RedFruit', 'BlueLegend', 'Mint'),
  `number_of_cubes`  ENUM('Eighteen', 'Thirty-six', 'Seventy-two'),
  `orders_id` INT(50) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `orders_id`),
  INDEX `fk_product_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_product_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `nargilemag`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `nargilemag`.`users_have_favorite_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`users_have_favorite_products` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`users_have_favorite_products` (
  `users_id` INT(10) UNSIGNED NOT NULL,
  `products_id` INT(50) NOT NULL,
  PRIMARY KEY (`users_id`, `products_id`),
  INDEX `fk_users_has_product_product1_idx` (`products_id` ASC),
  INDEX `fk_users_has_product_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_product_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `nargilemag`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_product_product1`
    FOREIGN KEY (`products_id`)
    REFERENCES `nargilemag`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
